--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaPigGuy/PiggyCustomEnchants
branches:
  - master
  - ssdhd
projects:
  PiggyCustomEnchants:
    path: ""
    icon: "resources/PCE_Icon.png"
    libs:
      - src: PoggitTestPlugins/FormAPI/libFormAPI
        version: ^1.3
      - src: PoggitTestPlugins/Commando/Commando
        version: ^0.6.0
...
